### ISSUE TITLE
Since Update to Capitan Error

### ISSUE THREAD

**Issue by Anzumana** [karandesai-96/yolog#15]
```
Traceback (most recent call last):
  File "/usr/local/bin/yolog", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/yolog/main.py", line 26, in main
    yolog_gen = YologGenerator(config_filepath)
  File "/Library/Python/2.7/site-packages/yolog/yolog_generator.py", line 79, in __init__
    getattr(self, self.config.get("color", "hash")), RESET)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in
 get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'color'
```

Is what i get when i try to run yolog.
I reinstalled pip and did a clean yolog after removing yolog with rm -rf.

**Comment by kdexd** [comment]
It is a problem with certain operating systems. While I overcome it, please try out the solution in #11. It should work until you uninstall it again :smile:

**Comment by kdexd** [comment]
[This comment](https://github.com/karandesai-96/yolog/issues/11#issuecomment-234981476) has a temporary solution.

**Comment by brunns** [comment]
I've just had the same issue, but I'm on Ubuntu not OSX.

**Comment by dimitrieh** [comment]
would very much like to have this fixed :)
